Repository develhope/Java27-progetto3-team1, pull requests merged in 2024-11, with the labels that each got.

#90 Feat/Subscription
  src/main/java/com/team1/dealerApp/subscription/Subscription.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionDTO.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionRepository.java
  src/main/java/com/team1/dealerApp/user/User.java
Labels: enhancement

#94 Add paypal support
  .gitignore
  pom.xml
  src/main/java/com/team1/dealerApp/config/PayPalConfig.java
  src/main/java/com/team1/dealerApp/config/SecurityConfig.java
  src/main/java/com/team1/dealerApp/error/ErrorControllerAdvice.java
  src/main/java/com/team1/dealerApp/paypal/PayPalController.java
  src/main/java/com/team1/dealerApp/paypal/PayPalService.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseController.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
  src/main/java/com/team1/dealerApp/rental/RentalController.java
  src/main/java/com/team1/dealerApp/rental/RentalService.java
  src/main/java/com/team1/dealerApp/subscription/Subscription.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionController.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionService.java
  src/main/java/com/team1/dealerApp/user/UserController.java
  src/main/java/com/team1/dealerApp/user/UserService.java
  src/main/java/com/team1/dealerApp/video/movie/CreateMovieDTO.java
  src/main/java/com/team1/dealerApp/video/movie/MovieController.java
  src/main/java/com/team1/dealerApp/video/movie/MovieDTO.java
  src/main/java/com/team1/dealerApp/video/movie/MovieMapper.java
  src/main/java/com/team1/dealerApp/video/movie/MovieRepository.java
  src/main/java/com/team1/dealerApp/video/movie/MovieService.java
  src/main/java/com/team1/dealerApp/video/tvshow/CreateShowDTO.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowController.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowMapper.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowRepository.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowService.java
  src/main/resources/application.yaml
Labels: bug, enhancement

#100 Demo branch aggiornato
  src/main/java/com/team1/dealerApp/video/movie/MovieController.java
  src/main/java/com/team1/dealerApp/video/movie/MovieService.java
Labels: bug

#103 Pages implementation
  src/main/java/com/team1/dealerApp/DealerAppApplication.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
  src/main/java/com/team1/dealerApp/rental/RentalService.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionController.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionRepository.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionService.java
  src/main/java/com/team1/dealerApp/user/UserController.java
  src/main/java/com/team1/dealerApp/user/UserService.java
  src/main/java/com/team1/dealerApp/utils/Pager.java
  src/main/java/com/team1/dealerApp/video/movie/MovieController.java
  src/main/java/com/team1/dealerApp/video/movie/MovieService.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowController.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowService.java
  src/test/java/com/team1/dealerApp/video/tvshow/TvShowServiceTest.java
Labels: bug

#102 Feat/rental pay pal
  src/main/java/com/team1/dealerApp/rental/CreateRentalDTO.java
  src/main/java/com/team1/dealerApp/rental/Rental.java
  src/main/java/com/team1/dealerApp/rental/RentalController.java
  src/main/java/com/team1/dealerApp/rental/RentalDTO.java
  src/main/java/com/team1/dealerApp/rental/RentalMapper.java
  src/main/java/com/team1/dealerApp/rental/RentalService.java
Labels: enhancement, fix

#104 Feat/payment
  src/main/java/com/team1/dealerApp/paypal/PayPalController.java
  src/main/java/com/team1/dealerApp/paypal/PayPalService.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseController.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
  src/main/java/com/team1/dealerApp/rental/RentalService.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionController.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionDTO.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionMapper.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionRepository.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionService.java
  src/main/java/com/team1/dealerApp/user/UserController.java
  src/main/java/com/team1/dealerApp/user/UserService.java
  src/main/java/com/team1/dealerApp/video/movie/MovieController.java
  src/main/java/com/team1/dealerApp/video/movie/MovieService.java
  src/main/java/com/team1/dealerApp/video/tvshow/CreateShowDTO.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowController.java
Labels: enhancement, fix

#107 Demo
  src/main/java/com/team1/dealerApp/error/ErrorControllerAdvice.java
  src/main/java/com/team1/dealerApp/rental/RentalService.java
  src/main/java/com/team1/dealerApp/subscription/Subscription.java
  src/main/java/com/team1/dealerApp/subscription/SubscriptionService.java
  src/main/java/com/team1/dealerApp/user/UserService.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowController.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowService.java
Labels: bug
