Repository develhope/Java27-progetto3-team1, pull requests merged in 2024-10, with the labels that each got.

#11 Feat/Video
  src/main/java/com/team1/dealerApp/entities/Movie.java
  src/main/java/com/team1/dealerApp/entities/TvShow.java
  src/main/java/com/team1/dealerApp/mappers/MovieMapper.java
  src/main/java/com/team1/dealerApp/mappers/TvShowMapper.java
  src/main/java/com/team1/dealerApp/models/Genre.java
  src/main/java/com/team1/dealerApp/models/Video.java
  src/main/java/com/team1/dealerApp/models/VideoStatus.java
  src/main/java/com/team1/dealerApp/models/dtos/MovieDTO.java
  src/main/java/com/team1/dealerApp/models/dtos/TvShowDTO.java
  src/main/java/com/team1/dealerApp/repositories/MovieRepository.java
  src/main/java/com/team1/dealerApp/repositories/TvShowRepository.java
Labels: enhancement

#10 Feat/user
  src/main/java/com/team1/dealerApp/entities/User.java
  src/main/java/com/team1/dealerApp/mappers/UserMapper.java
  src/main/java/com/team1/dealerApp/models/SubsciprionStatus.java
  src/main/java/com/team1/dealerApp/models/dtos/UserDTO.java
  src/main/java/com/team1/dealerApp/repositories/UserRepository.java
Labels: enhancement

#18 Add import for TvShow and Movie class
  src/main/java/com/team1/dealerApp/models/dtos/CreateUserDTO.java
  src/main/java/com/team1/dealerApp/models/dtos/UserDTO.java
Labels: bug

#44 Update README.md
  README.md
Labels: documentation

#39 Feat/test movie service
  src/main/java/com/team1/dealerApp/video/movie/MovieService.java
  src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
Labels: testing

#46 Add gitignore
  .gitignore
  .idea/.gitignore
Labels: documentation

#47 Feat/rental
  src/main/java/com/team1/dealerApp/rental/Rental.java
  src/main/java/com/team1/dealerApp/rental/RentalRepository.java
  src/main/java/com/team1/dealerApp/user/User.java
  src/main/java/com/team1/dealerApp/video/movie/Movie.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShow.java
Labels: enhancement

#48 Test class for TvShowServices & various fixes
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowController.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowRepository.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowService.java
  src/test/java/com/team1/dealerApp/video/tvshow/TvShowServiceTest.java
Labels: bug, testing

#49 Feat/rental
  src/main/java/com/team1/dealerApp/rental/CreateRentalDTO.java
  src/main/java/com/team1/dealerApp/rental/RentalController.java
  src/main/java/com/team1/dealerApp/rental/RentalDTO.java
  src/main/java/com/team1/dealerApp/rental/RentalMapper.java
  src/main/java/com/team1/dealerApp/rental/RentalRepository.java
  src/main/java/com/team1/dealerApp/rental/RentalService.java
  src/main/java/com/team1/dealerApp/rental/RentalStatus.java
  src/main/java/com/team1/dealerApp/user/UserController.java
  src/main/java/com/team1/dealerApp/user/UserService.java
Labels: enhancement

#50 Feat/Purchase
  README.md
  src/main/java/com/team1/dealerApp/purchase/OrderStatus.java
  src/main/java/com/team1/dealerApp/purchase/Purchase.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseRepository.java
Labels: enhancement

#53 Users registration system
  pom.xml
  src/main/java/com/team1/dealerApp/SecurityConfig.java
  src/main/java/com/team1/dealerApp/user/User.java
  src/main/java/com/team1/dealerApp/user/UserController.java
  src/main/java/com/team1/dealerApp/user/UserMapper.java
  src/main/java/com/team1/dealerApp/user/UserRepository.java
  src/main/java/com/team1/dealerApp/user/UserService.java
Labels: bug, enhancement

#52 Feat/test rental service
  src/main/java/com/team1/dealerApp/rental/Rental.java
  src/main/java/com/team1/dealerApp/rental/RentalMapper.java
  src/main/java/com/team1/dealerApp/rental/RentalService.java
  src/test/java/com/team1/dealerApp/rental/RentalServiceTest.java
Labels: testing

#54 Added Admin Entity
  src/main/java/com/team1/dealerApp/admin/Admin.java
  src/main/java/com/team1/dealerApp/admin/AdminDTO.java
  src/main/java/com/team1/dealerApp/admin/AdminMapper.java
  src/main/java/com/team1/dealerApp/admin/AdminRepository.java
  src/main/java/com/team1/dealerApp/admin/AdminService.java
  src/main/java/com/team1/dealerApp/admin/CreateAdminDTO.java
Labels: enhancement

#56 Feat/Purchase
  src/main/java/com/team1/dealerApp/purchase/CreatePurchaseDTO.java
  src/main/java/com/team1/dealerApp/purchase/Purchase.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseController.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseDTO.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseMapper.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseRepository.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
Labels: enhancement

#57 Feat/exception handler
  src/main/java/com/team1/dealerApp/error/ErrorControllerAdvice.java
  src/main/java/com/team1/dealerApp/error/ErrorDTO.java
  src/main/java/com/team1/dealerApp/video/movie/MovieController.java
Labels: enhancement

#59 Feat/exception handler user controller
  src/main/java/com/team1/dealerApp/user/UserController.java
Labels: enhancement

#65 Feat/admin controller
  src/main/java/com/team1/dealerApp/admin/AdminController.java
  src/main/java/com/team1/dealerApp/admin/AdminDTO.java
  src/main/java/com/team1/dealerApp/admin/AdminService.java
  src/test/java/com/team1/dealerApp/admin/AdminServiceTest.java
Labels: enhancement

#68 Feat/registration admin
  src/main/java/com/team1/dealerApp/admin/Admin.java
  src/main/java/com/team1/dealerApp/admin/AdminController.java
  src/main/java/com/team1/dealerApp/admin/AdminMapper.java
  src/main/java/com/team1/dealerApp/admin/AdminRepository.java
  src/main/java/com/team1/dealerApp/admin/AdminService.java
  src/main/java/com/team1/dealerApp/auth/AuthService.java
  src/main/java/com/team1/dealerApp/auth/AuthenticationController.java
  src/main/java/com/team1/dealerApp/config/SecurityConfig.java
  src/main/java/com/team1/dealerApp/user/UserController.java
  src/main/java/com/team1/dealerApp/user/UserService.java
  src/test/java/com/team1/dealerApp/admin/AdminServiceTest.java
Labels: enhancement

#70 Demo branch
  src/main/java/com/team1/dealerApp/admin/AdminRepository.java
  src/main/java/com/team1/dealerApp/auth/AuthService.java
  src/main/java/com/team1/dealerApp/error/ErrorControllerAdvice.java
  src/main/java/com/team1/dealerApp/error/ErrorDTO.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseMapper.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseRepository.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
  src/main/java/com/team1/dealerApp/video/movie/MovieUpdater.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowUpdater.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/java/com/team1/dealerApp/admin/AdminServiceTest.java
Labels: bug

#66 Feat/Test-User
  src/main/java/com/team1/dealerApp/user/UserService.java
  src/test/java/com/team1/dealerApp/user/UserServiceTest.java
Labels: testing

#75 Permissions
  src/main/java/com/team1/dealerApp/auth/AuthService.java
  src/main/java/com/team1/dealerApp/config/SecurityConfig.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseController.java
  src/main/java/com/team1/dealerApp/rental/RentalController.java
  src/main/java/com/team1/dealerApp/user/Role.java
  src/main/java/com/team1/dealerApp/video/movie/MovieController.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowController.java
Labels: enhancement

#82 Edit Admin registering method
  src/main/java/com/team1/dealerApp/auth/AuthService.java
Labels: bug

#85 Feat/check sales
  src/main/java/com/team1/dealerApp/auth/AuthService.java
  src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
  src/main/java/com/team1/dealerApp/rental/RentalService.java
  src/main/java/com/team1/dealerApp/user/CreateUserDTO.java
  src/main/java/com/team1/dealerApp/user/SubscriptionStatus.java
  src/main/java/com/team1/dealerApp/user/User.java
  src/main/java/com/team1/dealerApp/user/UserDTO.java
  src/main/java/com/team1/dealerApp/user/UserMapper.java
  src/main/java/com/team1/dealerApp/video/AgeRating.java
  src/main/java/com/team1/dealerApp/video/CheckSalesController.java
  src/main/java/com/team1/dealerApp/video/Video.java
  src/main/java/com/team1/dealerApp/video/movie/AdminMovieDTO.java
  src/main/java/com/team1/dealerApp/video/movie/Movie.java
  src/main/java/com/team1/dealerApp/video/movie/MovieController.java
  src/main/java/com/team1/dealerApp/video/movie/MovieDTO.java
  src/main/java/com/team1/dealerApp/video/movie/MovieMapper.java
  src/main/java/com/team1/dealerApp/video/movie/MovieService.java
  src/main/java/com/team1/dealerApp/video/tvshow/AdminTvShowDTO.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShow.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowController.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowDTO.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowMapper.java
  src/main/java/com/team1/dealerApp/video/tvshow/TvShowService.java
  src/test/java/com/team1/dealerApp/rental/RentalServiceTest.java
  src/test/java/com/team1/dealerApp/user/UserServiceTest.java
  src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
  src/test/java/com/team1/dealerApp/video/tvshow/TvShowServiceTest.java
Labels: enhancement
